### PR TITLE
Crop stage tests

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
Fixed bug in Bulk Density calculations
Added class to calculate soil test value (kgN/ha) from input data
Added method to call this class to the interface

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@Nibble-Byte can you please review this and let me know if it will work OK or cause any problems.
I have added a method into FieldNBalance\SVSModel\ModelInterface.cs which takes the inputs for soil test calculatons and returns a soil test value

``` c#
        public Dictionary<DateTime, double> GetSoilTestResult(DateTime testDate, double testValue, SampleDepths depthOfSample,
                                                       TestType typeOfTest, TestMoisture moistureOfTest,
                                                       SoilCategoris categoryOfSoil, SoilTextures textureOfSoil)
        {
            SoilTestConfig test = new SoilTestConfig(testDate, testValue, depthOfSample,
                                                       typeOfTest, moistureOfTest,
                                                       categoryOfSoil, textureOfSoil);
            return test.Result;
        }
```
It returns a Dictionary<DateTime, double> as I figured it would be simplist to call this for each test and them to give Dictionary<DateTime, double> nApplied for GetDailyNBalance(...

I have made the categorical inputs to GetSoilTestResult(.. into enums to ensure consistency inputs.  They are declaired in FieldNBalance\SVSModel\Configuration\InputCategories.cs.   There are enums for all of the inputs in this class but I have only used the ones that relate to the soil tests so far to check it doesn't cause any problems.  Please note that I have changed the existing SoilCategory SoilTexture and SampleDepth properties in the config from strings to enums.  Let me know if this causes any problems from your side and I can change them back to strings.  If this works nicely I could change all the categorical properties in the config to enums and implement the enumeration properly (at the moment I don't set values, just use them to enforce categories and link these to values in dictionaries) 
I am available today and tomorrow to make changes and then merge this if you think you can implement it from your side efficiently.

**Comment by Nibble-Byte** [comment]
Hi @HamishBrownPFR, The only concern I have here is that these changes are bundled with a refactor of the Constants as well.
I think that it should be fine, but I wont know until this is merged and I get started, Currently our frontend stores copies of all the strings that were needed for the Constants, but now that those are enums, there will need to be a ton of refactoring on our front and backend to ensure that everything else continues to work

**Comment by HamishBrownPFR** [comment]
@Nibble-Byte would it be better if I changed them back to strings to save  you the refactoring job in the short term.

**Comment by HamishBrownPFR** [comment]
@Nibble-Byte I have changed the inputs back to strings.  I will merge this pull request so you can have a go.  Please note I have added two more soil texture cagetories and changed the names of some soil textrure categories to remove spaces.  I have also added two soil depth cagetories and changed the names to remove spaces.  It would not be hard to change the names back if this is problematic. Its a hang over from trying to do them as enums

**Pull request merged**
