### PR TITLE
Chore: Model Code Refactor

### PR DESCRIPTION
**Pull request by Nibble-Byte**

### CODE REVIEW

**Comment by JBris** [comment]
@Nibble-Byte 

2 / 12 failed unit tests

I encountered a similar issue with my own branch. I think you might need to look at this one @HamishBrownPFR

**Comment by Nibble-Byte** [comment]
@JBris / @HamishBrownPFR That failing unit test should pass now.

Hamish and I need to have a call on monday/tuesday to discuss some of the changes I made.

**Comment by JBris** [comment]
@Nibble-Byte 

okay, all unit tests have passed. Will leave it to you to make the approval @HamishBrownPFR

**Review by HamishBrownPFR — APPROVED** [review]
Changes from the client side needed in response to changes in the API interface

**Pull request merged**
